# Generated by Django 6.0.2 on 2026-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
