# Generated by Django 6.0.2 on 2026-02-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0002_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10),
        ),
    ]
