# Generated by Django 6.0.2 on 2026-02-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0003_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('School', 'School'), ('Urgent', 'Urgent')], default='Personal', max_length=20),
        ),
    ]
